#!/usr/bin/env bash


################################################################################
### Head: Url
##

# * https://github.com/samwhelp/skel-project-plan/blob/gh-pages/demo/sh/standalone/bin/demo-ctrl

##
### Tail: Url
################################################################################


################################################################################
### Head: Init
##
set -e ## for Exit immediately if a command exits with a non-zero status.
THE_BASE_DIR_PATH="$(cd -- "$(dirname -- "$0")" ; pwd)"
THE_CMD_FILE_NAME="$(basename "$0")"
##
### Tail: Init
################################################################################


################################################################################
### Head: Util / Debug
##

util_debug_echo () {
	if is_debug; then
		echo "$@" 1>&2
	fi
}

util_error_echo () {
	echo "$@" 1>&2
}

##
### Head: Util / Debug
################################################################################


################################################################################
### Head: Base
##

## THE_BASE_DIR_PATH="$(cd -- "$(dirname -- "$0")" ; pwd)"

find_dir_path () {
	if ! [ -d "$(dirname -- "$1")" ]; then
		dirname -- "$1"
		return 1
	fi
	echo "$(cd -- "$(dirname -- "$1")" ; pwd)"
}

## THIS_BASE_DIR_PATH="$(find_dir_path "$0")"

## $ export DEBUG_SXHKDRC_CTRL=true
is_debug () {
	if [ "$DEBUG_SXHKDRC_CTRL" = "true" ]; then
		return 0
	fi

	return 1
}

is_not_debug () {
	! is_debug
}

base_var_init () {

	#THE_PLAN_DIR_PATH="$(find_dir_path "$THE_BASE_DIR_PATH/../.")"
	THE_PLAN_DIR_PATH="$(find_dir_path "$THE_BASE_DIR_PATH/.")"

	THE_CMD_VERSION='0.1'

	THE_CMD_DIR_PATH="${THE_BASE_DIR_PATH}"

	if [ "none${THE_CMD_FILE_NAME}" = 'none' ]; then
		THE_CMD_FILE_NAME='sxhkdrc-ctrl'
	fi

	THE_CMD_FILE_PATH="${THE_CMD_DIR_PATH}/$THE_CMD_FILE_NAME"

	## https://github.com/samwhelp/play-ubuntu-20.04-plan/blob/master/project/sxhkdrc-profile/sxhkdrc-ctrl/sxhkdrc-ctrl
	THE_SELF_UPDATE_URL='https://raw.githubusercontent.com/samwhelp/note-about-bspwm/gh-pages/_demo/project/sxhkdrc-profile/sxhkdrc-ctrl/sxhkdrc-ctrl'


	THE_TMP_DIR_PATH="/tmp"


	THE_ASSET_DIR_NAME="asset"
	THE_ASSET_DIR_PATH="$THE_PLAN_DIR_PATH/$THE_ASSET_DIR_NAME"

	THE_VAR_DIR_NAME="var"
	THE_VAR_DIR_PATH="$THE_PLAN_DIR_PATH/$THE_VAR_DIR_NAME"

	THE_PROFILE_DIR_NAME=".${THE_CMD_FILE_NAME}-profile"
	THE_PROFILE_DIR_PATH="$HOME/$THE_PROFILE_DIR_NAME"

	THE_PROJECT_DIR_NAME="${THE_CMD_FILE_NAME}"
	THE_PROJECT_DIR_PATH="$HOME/.local/share/$THE_PROJECT_DIR_NAME"

	THE_CONFIG_DIR_NAME="${THE_CMD_FILE_NAME}"
	THE_CONFIG_DIR_PATH="$HOME/.config/$THE_CONFIG_DIR_NAME"

	THE_CACHE_DIR_NAME="${THE_CMD_FILE_NAME}"
	THE_CACHE_DIR_PATH="$HOME/.cache/$THE_CACHE_DIR_NAME"




	## sxhkd
	THE_SXHKDRC_DIR_NAME="sxhkd"
	THE_SXHKDRC_DIR_PATH="$HOME/.config/$THE_SXHKDRC_DIR_NAME"

	THE_SXHKDRC_FILE_NAME="sxhkdrc"
	THE_SXHKDRC_FILE_PATH="$THE_SXHKDRC_DIR_PATH/$THE_SXHKDRC_FILE_NAME"

	## sxhkdrc-profile
	THE_SXHKDRC_PROFILE_DIR_NAME="sxhkdrc-profile"
	THE_SXHKDRC_PROFILE_DIR_PATH="$HOME/.local/share/$THE_SXHKDRC_PROFILE_DIR_NAME"

}

base_var_dump () {

	is_not_debug && return 0

	util_debug_echo
	util_debug_echo "################################################################################"
	util_debug_echo "### Head: var_dump"
	util_debug_echo "##"
	util_debug_echo "#"


	util_debug_echo "THE_PLAN_DIR_PATH=$THE_PLAN_DIR_PATH"

	util_debug_echo "THE_CMD_FILE_NAME=$THE_CMD_FILE_NAME"
	util_debug_echo "THE_CMD_FILE_PATH=$THE_CMD_FILE_PATH"
	util_debug_echo "THE_CMD_DIR_PATH=$THE_CMD_DIR_PATH"

	util_debug_echo "THE_SELF_UPDATE_URL=$THE_SELF_UPDATE_URL"


	util_debug_echo "THE_TMP_DIR_PATH=$THE_TMP_DIR_PATH"


	util_debug_echo "THE_ASSET_DIR_NAME=$THE_ASSET_DIR_NAME"
	util_debug_echo "THE_ASSET_DIR_PATH=$THE_ASSET_DIR_PATH"

	util_debug_echo "THE_VAR_DIR_NAME=$THE_VAR_DIR_NAME"
	util_debug_echo "THE_VAR_DIR_PATH=$THE_VAR_DIR_PATH"




	util_debug_echo "THE_PROFILE_DIR_NAME=$THE_PROFILE_DIR_NAME"
	util_debug_echo "THE_PROFILE_DIR_PATH=$THE_PROFILE_DIR_PATH"

	util_debug_echo "THE_PROJECT_DIR_NAME=$THE_PROJECT_DIR_NAME"
	util_debug_echo "THE_PROJECT_DIR_PATH=$THE_PROJECT_DIR_PATH"

	util_debug_echo "THE_CONFIG_DIR_NAME=$THE_CONFIG_DIR_NAME"
	util_debug_echo "THE_CONFIG_DIR_PATH=$THE_CONFIG_DIR_PATH"

	util_debug_echo "THE_CACHE_DIR_NAME=$THE_CACHE_DIR_NAME"
	util_debug_echo "THE_CACHE_DIR_PATH=$THE_CACHE_DIR_PATH"




	util_debug_echo "THE_SXHKDRC_DIR_NAME=$THE_SXHKDRC_DIR_NAME"
	util_debug_echo "THE_SXHKDRC_DIR_PATH=$THE_SXHKDRC_DIR_PATH"

	util_debug_echo "THE_SXHKDRC_FILE_NAME=$THE_SXHKDRC_FILE_NAME"
	util_debug_echo "THE_SXHKDRC_FILE_PATH=$THE_SXHKDRC_FILE_PATH"

	util_debug_echo "THE_SXHKDRC_PROFILE_DIR_NAME=$THE_SXHKDRC_PROFILE_DIR_NAME"
	util_debug_echo "THE_SXHKDRC_PROFILE_DIR_PATH=$THE_SXHKDRC_PROFILE_DIR_PATH"


	util_debug_echo "#"
	util_debug_echo "##"
	util_debug_echo "### Tail: var_dump"
	util_debug_echo "################################################################################"
	util_debug_echo
}


base_var_init

base_var_dump

##
### Tail: Base
################################################################################


################################################################################
### Head: Util / Command
##

is_function_exist () {
	if type -p "$1" > /dev/null; then
		return 0
	else
		return 1
	fi
}

# is_command_exist () {
# 	if command -v "$1" > /dev/null; then
# 		return 0
# 	else
# 		return 1
# 	fi
# }

is_command_exist () {
	if [ -x "$(command -v $1)" ]; then
		return 0
	else
		return 1
	fi
}

##
### Tail: Util / Command
################################################################################


################################################################################
### Head: Util / Process
##

util_stop_all ()  {

	if is_command_exist 'pkill'; then
		util_stop_all_by_pkill "$1"
		return 0
	fi

	if is_command_exist 'killall'; then
		util_stop_all_by_killall "$1"
		return 0
	fi

	return 0
}

util_stop_all_by_pkill () {

	if pkill "$1"; then
		return 0
	fi

	return 0
}

util_stop_all_by_killall () {

	if killall -q -9 "$1"; then
		return 0
	fi

	return 0

}

##
### Tail: Util / Process
################################################################################


################################################################################
### Head: Util / SubCmd
##

sub_cmd_find_function_name () {
	echo "sub_run_$1"
}

##
### Tail: Util / SubCmd
################################################################################


################################################################################
### Head: Util / SelfUpdate
##

util_make_bin_dir () {
	mkdir -p "$HOME/bin"
}

util_make_tmp_dir () {
	THE_TMP_DIR_PATH="/tmp/tmp.$$.$RANDOM"
	mkdir "$THE_TMP_DIR_PATH"
}

util_self_update_download_to_tmp_dir () {

	local tmp_file_path="${THE_TMP_DIR_PATH}/${THE_CMD_FILE_NAME}"

	wget -c "$THE_SELF_UPDATE_URL" -O "$tmp_file_path"

}

util_self_update_install_from_tmp_dir () {

	local tmp_file_path="${THE_TMP_DIR_PATH}/${THE_CMD_FILE_NAME}"

	echo "install -m 755 $tmp_file_path $THE_CMD_FILE_PATH"
	install -m 755 "$tmp_file_path" "$THE_CMD_FILE_PATH"

}

util_self_update_check_cmd_exists () {

	if ! [ -f "$THE_CMD_FILE_PATH" ]; then ## file not exists
		return 0
	fi


	echo "File is exists:" "$THE_CMD_FILE_PATH"
	echo

	echo "Try to backup:"
	echo

	local now=$(date +%Y%m%d_%s)
	local bak_dir_path="${THE_CMD_FILE_PATH}.bak"
	local bak_file_path="${bak_dir_path}/${THE_CMD_FILE_NAME}.bak.$now"

	mkdir -p $bak_dir_path

	mv -v "$THE_CMD_FILE_PATH" "${bak_file_path}"

	if [ "$?" != "0" ]; then
		echo
		echo 'Backup Failure!'
		exit 1
	fi

	echo

	return 0
}

util_self_update_print_version () {
	echo
	echo "Current Version:"

	"$THE_CMD_FILE_PATH" version
}

util_self_update () {

	util_make_bin_dir

	util_make_tmp_dir

	util_self_update_download_to_tmp_dir

	util_self_update_check_cmd_exists && util_self_update_install_from_tmp_dir


	util_self_update_print_version

}


main_version () {
	echo $THE_CMD_VERSION
}

util_self_actions () {
	grep '^sub_run' "${THE_CMD_FILE_PATH}" | cut -d ' ' -f 1 | awk -F 'sub_run_' '{print $2}' | sort -u
}

##
### Tail: Util / SelfUpdate
################################################################################


################################################################################
### Head: Sys
##

is_sxhkdrc_dir () {

	local dir_path="$1"
	local sxhkdrc_file_path="$dir_path/$THE_SXHKDRC_FILE_NAME" ## ~/.config/sxhkdrc-profile/demo/sxhkd.conf

	if [ ! -f "$sxhkdrc_file_path" ]; then ## check ~/.config/sxhkdrc-profile/demo/sxhkd.conf
		return 1
	fi

	return 0
}

is_not_sxhkdrc_dir () {

	local dir_path="$1"
	local sxhkdrc_file_path="$dir_path/$THE_SXHKDRC_FILE_NAME" ## ~/.config/sxhkdrc-profile/demo/sxhkd.conf

	if [ -f "$sxhkdrc_file_path" ]; then ## check ~/.config/sxhkdrc-profile/demo/sxhkd.conf
		return 1
	fi

	return 0

}

sxhkdrc_find_dir_path_by_name () {
	local name="$1"
	echo "$THE_SXHKDRC_PROFILE_DIR_PATH/$name"
}


sxhkdrc_check_sxhkdrc_dir_exists () {

	local sxhkdrc_dir_name="$THE_SXHKDRC_DIR_NAME"
	local sxhkdrc_dir_path="$THE_SXHKDRC_DIR_PATH"

	if ! [ -a "$sxhkdrc_dir_path" ]; then ## file not exists
		return 0
	fi


	if [ -h "$sxhkdrc_dir_path" ]; then ## ~/.config/sxhkd is symbolic link
		return 0
	fi



	util_error_echo "## Dir is exists:" "$sxhkdrc_dir_path"
	util_error_echo

	util_error_echo "## Try to backup:"
	util_error_echo

	local now="$(date +%Y%m%d_%s)"
	local bak_dir_path="${HOME}/.backup/${sxhkdrc_dir_name}.bak"
	local bak_target_path="${bak_dir_path}/${sxhkdrc_dir_name}.bak.${now}"

	util_error_echo "mkdir -p ${bak_dir_path}"
	mkdir -p "${bak_dir_path}"


	util_error_echo "cp -a ${sxhkdrc_dir_path} ${bak_target_path}"
	cp -a "${sxhkdrc_dir_path}" "${bak_target_path}"

	if [ "$?" != "0" ]; then
		util_error_echo
		util_error_echo '## Backup Failure!'
		#exit 1
		return 1
	fi

	util_error_echo


	return 0
}


sxhkdrc_profile_init_dir () {

	if ! [ -d "$THE_SXHKDRC_PROFILE_DIR_PATH" ]; then
		##echo "$THE_SXHKDRC_PROFILE_DIR_PATH"
		mkdir -p "$THE_SXHKDRC_PROFILE_DIR_PATH"
	fi

	return 0
}


sxhkdrc_repo_clone () {

	## $ sxhkdrc-get demo

	local name="$1"
	local repo_url="$2"

	if [ "none$name" == 'none' ]; then
		name='default'
	fi

	util_error_echo "mkdir -p $THE_SXHKDRC_PROFILE_DIR_PATH"
	mkdir -p "$THE_SXHKDRC_PROFILE_DIR_PATH"

	util_error_echo "cd $THE_SXHKDRC_PROFILE_DIR_PATH"
	cd "$THE_SXHKDRC_PROFILE_DIR_PATH" ## cd ~/.local/share/sxhkdrc-profile


	if [ -d "$name" ]; then
		util_error_echo
		util_error_echo "## Is Exists:" "$THE_SXHKDRC_PROFILE_DIR_PATH/$name"
		return 0;
	fi

	util_error_echo "git clone --recursive $repo_url $name "
	git clone --recursive "$repo_url" "$name"  ## git clone --recursive https://github.com/conformal/sxhkd.git demo

	## $ man cd
	util_error_echo "cd $OLDPWD"
	cd "$OLDPWD"

}

##
### Tail: Sys
################################################################################


################################################################################
### Head: Model xephyr
##

## Original Script
## https://github.com/worron/awesome-config/blob/master/scripts/run-with-xephyr.sh

## Arch Wiki / Xephyr
## https://wiki.archlinux.org/index.php/Xephyr

mod_xephyr () {
	#echo "mod_xephyr"
	#echo "$@"

	if ! is_command_exist 'Xephyr'; then

		util_error_echo
		util_error_echo '## Need: Xephyr'
		util_error_echo '# * https://archlinux.org/packages/extra/x86_64/xorg-server-xephyr/'
		util_error_echo
		util_error_echo '## Manjaro Install:'
		util_error_echo '# $ pamac install xorg-server-xephyr'
		util_error_echo
		util_error_echo '## Ubuntu Install:'
		util_error_echo '# $ sudo apt-get install xserver-xephyr'
		util_error_echo

		return 1
	fi

	mod_xephyr_run_sxhkd "$1" "$2"

}


mod_xephyr_run_sxhkd () {

	## screen_size
	local screen_size="1280x720"
	local config_file_path


	if [ "none$1" != "none" ]; then
		screen_size="$1"
	fi

	if [ "none$2" != "none" ]; then
		config_file_path="$2"
	fi

	if ! [ -f "$config_file_path" ]; then
		config_file_path=""
	fi

	## run Xephyr
	#Xephyr :100 -ac -screen 1280x720 &
	Xephyr :100 -ac -screen "$screen_size" &
	XEPHYR_PID="$!"
	sleep 0.5

	## run sxhkd
	##DISPLAY=:100 sxhkd

	if [ "none$config_file_path" = "none" ]; then
		util_error_echo "DISPLAY=:100 sxhkd"
		DISPLAY=:100 sxhkd
	else
		util_error_echo "DISPLAY=:100 sxhkd -c $config_file_path"
		DISPLAY=:100 sxhkd -c $config_file_path
	fi

	## make sure kill Xephyr
	kill ${XEPHYR_PID}

}



##
### Tail: Model xephyr
################################################################################


################################################################################
### Head: Model fzf
##

mod_fzf () {
	#echo "mod_fzf"
	#echo "$@"

	if ! is_command_exist 'fzf'; then

		util_error_echo '## Need: fzf'
		util_error_echo '# * https://github.com/junegunn/fzf'
		util_error_echo
		util_error_echo '## Manjaro Install:'
		util_error_echo '# $ pamac install fzf'
		util_error_echo
		util_error_echo '## Ubuntu Install:'
		util_error_echo '# $ sudo apt-get install fzf'
		util_error_echo

		return 1
	fi


	local selected="$(mod_sxhkdrc_profile_list | fzf)"

	util_error_echo
	util_error_echo "## Selected:"
	#util_error_echo

	if [ "none$selected" = "none" ]; then
		util_error_echo "# ! None Selected !"
		return 1
	fi

	util_error_echo "# [ $selected ]"
	mod_sxhkdrc_profile_set "$selected"

}

##
### Tail: Model fzf
################################################################################


################################################################################
### Head: Model mod_sxhkdrc_profile_default
##

mod_sxhkdrc_profile_default () {
	mod_sxhkdrc_profile_set 'default'
}

##
### Tail: Model mod_sxhkdrc_profile_default
################################################################################


################################################################################
### Head: Model mod_sxhkdrc_profile_list
##



mod_sxhkdrc_profile_list () {
	#echo "mod_sxhkdrc_profile_list"
	#echo "$@"

	# sxhkdrc-ctrl list

	local name=''
	local dir_path=''

	sxhkdrc_profile_init_dir

	cd "$THE_SXHKDRC_PROFILE_DIR_PATH"

	## for name in $(ls ./ -1); do
	for name in *; do
		dir_path="$THE_SXHKDRC_PROFILE_DIR_PATH/$name" ## ~/.local/share/sxhkdrc-profile/demo
		if is_not_sxhkdrc_dir "$dir_path"; then ## check ~/.local/share/sxhkdrc-profile/demo/sxhkd.conf
			continue
		fi

		echo "$name"
	done

	cd "$OLDPWD"

}

##
### Tail: Model mod_sxhkdrc_profile_list
################################################################################


################################################################################
### Head: Model mod_sxhkdrc_profile_get
##

mod_sxhkdrc_profile_get () {

	#echo "mod_sxhkdrc_profile_get"
	#echo "$@"

	# sxhkdrc-ctrl get

	local target_path="$THE_SXHKDRC_DIR_PATH" ## ~/.config/sxhkd
	local dir_path="$(LANG=C file "$target_path" | awk -F ' symbolic link to ' '{print $2}')"
	local name="$(basename "$dir_path")"

	echo $name

}

##
### Tail: Model mod_sxhkdrc_profile_get
################################################################################


################################################################################
### Head: Model mod_sxhkdrc_profile_set
##

mod_sxhkdrc_profile_set () {
	#echo "mod_sxhkdrc_profile_set"
	#echo "$@"


	## $ sxhkdrc-ctrl set demo

	local name="$1"
	local source_dir_path="$THE_SXHKDRC_PROFILE_DIR_PATH/$name"
	local target_dir_path="$THE_SXHKDRC_DIR_PATH"

	#echo "target_dir_path=$target_dir_path"
	#echo "source_dir_path=$source_dir_path"

	if is_not_sxhkdrc_dir "$source_dir_path"; then ## check ~/.config/sxhkdrc-profile/demo/sxhkd.conf
		util_error_echo
		util_error_echo "## Not Valid Sxhkdrc Dir: "
		util_error_echo
		util_error_echo "$source_dir_path"
		util_error_echo
		util_error_echo '## Please Run:'
		util_error_echo
		util_error_echo '# to find valid sxhkdrc dir.'
		util_error_echo '$ sxhkdrc-ctrl list'
		util_error_echo
		util_error_echo '# to select valid sxhkdrc dir.'
		util_error_echo '$ sxhkdrc-ctrl fzf'
		util_error_echo
		return 1
	fi

	sxhkdrc_check_sxhkdrc_dir_exists


	if [ -h "$target_dir_path" ]; then ## ~/.config/sxhkd is symbolic link
		util_error_echo
		util_error_echo "rm -f $target_dir_path"
		rm -f "$target_dir_path"
	else
		util_error_echo
		util_error_echo "rm -rf $target_dir_path"
		rm -rf "$target_dir_path"
	fi


	util_error_echo
	util_error_echo "ln -sf $source_dir_path $target_dir_path"
	ln -sf "$source_dir_path" "$target_dir_path"


	util_error_echo
	util_error_echo "file $target_dir_path"
	file "$target_dir_path"

}


##
### Tail: Model mod_sxhkdrc_profile_set
################################################################################


################################################################################
### Head: Model sxhkdrc_profile_install
##

sxhkdrc_profile_install () {

	## $ sxhkdrc-ctrl install demo https://github.com/samwhelp/note-about-bspwm.git

	local name="$1"
	local repo_url="$2"

	util_error_echo
	sxhkdrc_repo_clone "$name" "$repo_url"
	util_error_echo

}

##
### Tail: Model sxhkdrc_profile_install
################################################################################


################################################################################
### Head: Model mod_sxhkdrc_profile_remove
##

mod_sxhkdrc_profile_remove () {

	## $ sxhkdrc-ctrl remove demo

	local name="$1"
	#echo $name

	sxhkdrc_profile_init_dir

	util_error_echo "cd $THE_SXHKDRC_PROFILE_DIR_PATH"
	cd "$THE_SXHKDRC_PROFILE_DIR_PATH" ## cd ~/.local/share/sxhkdrc-profile

	local dir_path="./$name"

	if [ ! -d "$dir_path" ]; then ## check ~/.local/share/.sxhkdrc-profile/demo
		util_error_echo
		util_error_echo "## Dir not exists: "
		util_error_echo
		util_error_echo "$name"
		util_error_echo
		return 1
	fi

	##mod_sxhkdrc_profile_default

	util_error_echo "rm -rf $dir_path"
	rm -rf "$dir_path"

	util_error_echo "cd $OLDPWD"
	cd "$OLDPWD"

}

##
### Tail: Model mod_sxhkdrc_profile_remove
################################################################################


################################################################################
### Head: SubCmd
##

sub_run_help () {
	main_usage "$@"
}

sub_run_version () {
	main_version "$@"
}

sub_run_self_update () {
	util_self_update "$@"
}

sub_run_self_actions () {
	util_self_actions "$@"
}



sub_run_xephyr () {
	#echo "sub_run_xephyr"
	mod_xephyr "$@"
}


sub_run_fzf () {
	#echo "sub_run_fzf"
	mod_fzf "$@"
}


sub_run_default () {
	#echo "sub_run_default"
	mod_sxhkdrc_profile_default
}


sub_run_list () {
	#echo "sub_run_list"
	mod_sxhkdrc_profile_list "$@"
}


sub_run_get () {
	#echo "sub_run_get"
	mod_sxhkdrc_profile_get "$@"
}


sub_run_set () {
	#echo "sub_run_set"
	mod_sxhkdrc_profile_set "$@"
}


sub_run_install () {
	#echo "sub_run_install"
	sxhkdrc_profile_install "$@"
}


sub_run_remove () {
	#echo "sub_run_remove"
	mod_sxhkdrc_profile_remove "$@"
}

##
### Tail: SubCmd
################################################################################


################################################################################
### Head: Main
##

main_usage () {
	##local cmd_name="$0"
	local cmd_name="$THE_CMD_FILE_NAME"

cat << EOF
Usage:
	$ $cmd_name [action]

Example:

	## help

		$ $cmd_name
		$ $cmd_name help

	## version

		$ $cmd_name version

	## self_update

		$ $cmd_name self_update

	## self_actions

		$ $cmd_name self_actions

	## xephyr

		$ $cmd_name xephyr

		$ $cmd_name xephyr 1280x720

	## fzf

		$ $cmd_name fzf

	## profile

		$ $cmd_name default

		$ $cmd_name list

		$ $cmd_name get

		$ $cmd_name set demo

		$ $cmd_name install demo https://github.com/samwhelp/note-about-bspwm.git

		$ $cmd_name remove demo


Debug:
	$ export DEBUG_SXHKDRC_CTRL=true

EOF

}

main_check_args_size () {
	if [ $1 -le 0 ]; then
		shift
		main_run_default_sub_cmd "$@"
		exit 1
	fi
}

main_run_default_sub_cmd () {
	main_usage "$@"
}

main_run_sub_cmd () {

	local sub_cmd="$1"

	shift

	local function_name=$(sub_cmd_find_function_name "$sub_cmd")

	## if ! command -v $function_name > /dev/null; then
	if ! type -p $function_name > /dev/null; then
		util_debug_echo "[Debug] sub_cmd_function_not_exist: sub_cmd=$sub_cmd; function_name=$function_name"

		echo
		main_run_default_sub_cmd "$@"
		return 1
	fi

	"$function_name" "$@" ## run sub cmd function


}

## Start
main_check_args_size $# "$@"

main_run_sub_cmd "$@"

##
### Tail: Main
################################################################################
