#!/usr/bin/env bash


################################################################################
### Head: Url
##

## * https://github.com/samwhelp/skel-project-plan/blob/gh-pages/demo/sh/standalone/bin/demo-ctrl
## * https://github.com/samwhelp/note-about-bspwm/blob/gh-pages/_demo/project/bspwmrc-profile/bspwmrc-get/bspwmrc-get

##
### Tail: Url
################################################################################


################################################################################
### Head: Init
##
set -e ## for Exit immediately if a command exits with a non-zero status.
THE_BASE_DIR_PATH="$(cd -- "$(dirname -- "$0")" ; pwd)"
THE_CMD_FILE_NAME="$(basename "$0")"
##
### Tail: Init
################################################################################


################################################################################
### Head: Util / Debug
##

util_debug_echo () {
	if is_debug; then
		echo "$@" 1>&2
	fi
}

util_error_echo () {
	echo "$@" 1>&2
}

##
### Head: Util / Debug
################################################################################


################################################################################
### Head: Base
##

## THE_BASE_DIR_PATH="$(cd -- "$(dirname -- "$0")" ; pwd)"

find_dir_path () {
	if ! [ -d "$(dirname -- "$1")" ]; then
		dirname -- "$1"
		return 1
	fi
	echo "$(cd -- "$(dirname -- "$1")" ; pwd)"
}

## THIS_BASE_DIR_PATH="$(find_dir_path "$0")"

## $ export DEBUG_BSPWMRC_GET=true
is_debug () {
	if [ "$DEBUG_BSPWMRC_GET" = "true" ]; then
		return 0
	fi

	return 1
}

is_not_debug () {
	! is_debug
}

base_var_init () {

	#THE_PLAN_DIR_PATH="$(find_dir_path "$THE_BASE_DIR_PATH/../.")"
	THE_PLAN_DIR_PATH="$(find_dir_path "$THE_BASE_DIR_PATH/.")"

	THE_CMD_VERSION='0.1'

	THE_CMD_DIR_PATH="${THE_BASE_DIR_PATH}"

	if [ "none${THE_CMD_FILE_NAME}" = 'none' ]; then
		THE_CMD_FILE_NAME='bspwmrc-get'
	fi

	THE_CMD_FILE_PATH="${THE_CMD_DIR_PATH}/$THE_CMD_FILE_NAME"

	## https://github.com/samwhelp/note-about-bspwm/blob/gh-pages/_demo/project/bspwmrc-profile/bspwmrc-get/bspwmrc-get
	THE_SELF_UPDATE_URL='https://raw.githubusercontent.com/samwhelp/note-about-bspwm/gh-pages/_demo/project/bspwmrc-profile/bspwmrc-get/bspwmrc-get'


	THE_TMP_DIR_PATH="/tmp"


	THE_ASSET_DIR_NAME="asset"
	THE_ASSET_DIR_PATH="$THE_PLAN_DIR_PATH/$THE_ASSET_DIR_NAME"

	THE_VAR_DIR_NAME="var"
	THE_VAR_DIR_PATH="$THE_PLAN_DIR_PATH/$THE_VAR_DIR_NAME"

	THE_PROFILE_DIR_NAME=".${THE_CMD_FILE_NAME}-profile"
	THE_PROFILE_DIR_PATH="$HOME/$THE_PROFILE_DIR_NAME"

	THE_PROJECT_DIR_NAME="${THE_CMD_FILE_NAME}"
	THE_PROJECT_DIR_PATH="$HOME/.local/share/$THE_PROJECT_DIR_NAME"

	THE_CONFIG_DIR_NAME="${THE_CMD_FILE_NAME}"
	THE_CONFIG_DIR_PATH="$HOME/.config/$THE_CONFIG_DIR_NAME"

	THE_CACHE_DIR_NAME="${THE_CMD_FILE_NAME}"
	THE_CACHE_DIR_PATH="$HOME/.cache/$THE_CACHE_DIR_NAME"




	## bspwm
	THE_BSPWMRC_DIR_NAME="bspwm"
	THE_BSPWMRC_DIR_PATH="$HOME/.config/$THE_BSPWMRC_DIR_NAME"

	THE_BSPWMRC_FILE_NAME="bspwm.conf"
	THE_BSPWMRC_FILE_PATH="$THE_BSPWMRC_DIR_PATH/$THE_BSPWMRC_FILE_NAME"

	## bspwmrc-profile
	THE_BSPWMRC_PROFILE_DIR_NAME="bspwmrc-profile"
	THE_BSPWMRC_PROFILE_DIR_PATH="$HOME/.local/share/$THE_BSPWMRC_PROFILE_DIR_NAME"

}

base_var_dump () {

	is_not_debug && return 0

	util_debug_echo
	util_debug_echo "################################################################################"
	util_debug_echo "### Head: var_dump"
	util_debug_echo "##"
	util_debug_echo "#"


	util_debug_echo "THE_PLAN_DIR_PATH=$THE_PLAN_DIR_PATH"

	util_debug_echo "THE_CMD_FILE_NAME=$THE_CMD_FILE_NAME"
	util_debug_echo "THE_CMD_FILE_PATH=$THE_CMD_FILE_PATH"
	util_debug_echo "THE_CMD_DIR_PATH=$THE_CMD_DIR_PATH"

	util_debug_echo "THE_SELF_UPDATE_URL=$THE_SELF_UPDATE_URL"


	util_debug_echo "THE_TMP_DIR_PATH=$THE_TMP_DIR_PATH"


	util_debug_echo "THE_ASSET_DIR_NAME=$THE_ASSET_DIR_NAME"
	util_debug_echo "THE_ASSET_DIR_PATH=$THE_ASSET_DIR_PATH"

	util_debug_echo "THE_VAR_DIR_NAME=$THE_VAR_DIR_NAME"
	util_debug_echo "THE_VAR_DIR_PATH=$THE_VAR_DIR_PATH"




	util_debug_echo "THE_PROFILE_DIR_NAME=$THE_PROFILE_DIR_NAME"
	util_debug_echo "THE_PROFILE_DIR_PATH=$THE_PROFILE_DIR_PATH"

	util_debug_echo "THE_PROJECT_DIR_NAME=$THE_PROJECT_DIR_NAME"
	util_debug_echo "THE_PROJECT_DIR_PATH=$THE_PROJECT_DIR_PATH"

	util_debug_echo "THE_CONFIG_DIR_NAME=$THE_CONFIG_DIR_NAME"
	util_debug_echo "THE_CONFIG_DIR_PATH=$THE_CONFIG_DIR_PATH"

	util_debug_echo "THE_CACHE_DIR_NAME=$THE_CACHE_DIR_NAME"
	util_debug_echo "THE_CACHE_DIR_PATH=$THE_CACHE_DIR_PATH"




	util_debug_echo "THE_BSPWMRC_DIR_NAME=$THE_BSPWMRC_DIR_NAME"
	util_debug_echo "THE_BSPWMRC_DIR_PATH=$THE_BSPWMRC_DIR_PATH"

	util_debug_echo "THE_BSPWMRC_FILE_NAME=$THE_BSPWMRC_FILE_NAME"
	util_debug_echo "THE_BSPWMRC_FILE_PATH=$THE_BSPWMRC_FILE_PATH"

	util_debug_echo "THE_BSPWMRC_PROFILE_DIR_NAME=$THE_BSPWMRC_PROFILE_DIR_NAME"
	util_debug_echo "THE_BSPWMRC_PROFILE_DIR_PATH=$THE_BSPWMRC_PROFILE_DIR_PATH"


	util_debug_echo "#"
	util_debug_echo "##"
	util_debug_echo "### Tail: var_dump"
	util_debug_echo "################################################################################"
	util_debug_echo
}


base_var_init

base_var_dump

##
### Tail: Base
################################################################################


################################################################################
### Head: Util / Command
##

is_function_exist () {
	if type -p "$1" > /dev/null; then
		return 0
	else
		return 1
	fi
}

# is_command_exist () {
# 	if command -v "$1" > /dev/null; then
# 		return 0
# 	else
# 		return 1
# 	fi
# }

is_command_exist () {
	if [ -x "$(command -v $1)" ]; then
		return 0
	else
		return 1
	fi
}

##
### Tail: Util / Command
################################################################################


################################################################################
### Head: Util / Process
##

util_stop_all ()  {

	if is_command_exist 'pkill'; then
		util_stop_all_by_pkill "$1"
		return 0
	fi

	if is_command_exist 'killall'; then
		util_stop_all_by_killall "$1"
		return 0
	fi

	return 0
}

util_stop_all_by_pkill () {

	if pkill "$1"; then
		return 0
	fi

	return 0
}

util_stop_all_by_killall () {

	if killall -q -9 "$1"; then
		return 0
	fi

	return 0

}

##
### Tail: Util / Process
################################################################################


################################################################################
### Head: Util / SubCmd
##

sub_cmd_find_function_name () {
	echo "sub_run_$1"
}

##
### Tail: Util / SubCmd
################################################################################


################################################################################
### Head: Util / SelfUpdate
##

util_make_bin_dir () {
	mkdir -p "$HOME/bin"
}

util_make_tmp_dir () {
	THE_TMP_DIR_PATH="/tmp/tmp.$$.$RANDOM"
	mkdir "$THE_TMP_DIR_PATH"
}

util_self_update_download_to_tmp_dir () {

	local tmp_file_path="${THE_TMP_DIR_PATH}/${THE_CMD_FILE_NAME}"

	wget -c "$THE_SELF_UPDATE_URL" -O "$tmp_file_path"

}

util_self_update_install_from_tmp_dir () {

	local tmp_file_path="${THE_TMP_DIR_PATH}/${THE_CMD_FILE_NAME}"

	echo "install -m 755 $tmp_file_path $THE_CMD_FILE_PATH"
	install -m 755 "$tmp_file_path" "$THE_CMD_FILE_PATH"

}

util_self_update_check_cmd_exists () {

	if ! [ -f "$THE_CMD_FILE_PATH" ]; then ## file not exists
		return 0
	fi


	echo "File is exists:" "$THE_CMD_FILE_PATH"
	echo

	echo "Try to backup:"
	echo

	local now=$(date +%Y%m%d_%s)
	local bak_dir_path="${THE_CMD_FILE_PATH}.bak"
	local bak_file_path="${bak_dir_path}/${THE_CMD_FILE_NAME}.bak.$now"

	mkdir -p $bak_dir_path

	mv -v "$THE_CMD_FILE_PATH" "${bak_file_path}"

	if [ "$?" != "0" ]; then
		echo
		echo 'Backup Failure!'
		exit 1
	fi

	echo

	return 0
}

util_self_update_print_version () {
	echo
	echo "Current Version:"

	"$THE_CMD_FILE_PATH" version
}

util_self_update () {

	util_make_bin_dir

	util_make_tmp_dir

	util_self_update_download_to_tmp_dir

	util_self_update_check_cmd_exists && util_self_update_install_from_tmp_dir


	util_self_update_print_version

}


main_version () {
	echo $THE_CMD_VERSION
}

util_self_actions () {
	grep '^sub_run' "${THE_CMD_FILE_PATH}" | cut -d ' ' -f 1 | awk -F 'sub_run_' '{print $2}' | sort -u
}

##
### Tail: Util / SelfUpdate
################################################################################


################################################################################
### Head: Sys
##

is_bspwmrc_dir () {

	local dir_path="$1"
	local bspwmrc_file_path="$dir_path/$THE_BSPWMRC_FILE_NAME" ## ~/.config/bspwmrc-profile/demo/bspwm.conf

	if [ ! -f "$bspwmrc_file_path" ]; then ## check ~/.config/bspwmrc-profile/demo/bspwm.conf
		return 1
	fi

	return 0
}

is_not_bspwmrc_dir () {

	local dir_path="$1"
	local bspwmrc_file_path="$dir_path/$THE_BSPWMRC_FILE_NAME" ## ~/.config/bspwmrc-profile/demo/bspwm.conf

	if [ -f "$bspwmrc_file_path" ]; then ## check ~/.config/bspwmrc-profile/demo/bspwm.conf
		return 1
	fi

	return 0

}

bspwmrc_find_dir_path_by_name () {
	local name="$1"
	echo "$THE_BSPWMRC_PROFILE_DIR_PATH/$name"
}


bspwmrc_check_bspwmrc_dir_exists () {

	local bspwmrc_dir_name="$THE_BSPWMRC_DIR_NAME"
	local bspwmrc_dir_path="$THE_BSPWMRC_DIR_PATH"

	if ! [ -a "$bspwmrc_dir_path" ]; then ## file not exists
		return 0
	fi


	if [ -h "$bspwmrc_dir_path" ]; then ## ~/.config/bspwm is symbolic link
		return 0
	fi



	util_error_echo "## Dir is exists:" "$bspwmrc_dir_path"
	util_error_echo

	util_error_echo "## Try to backup:"
	util_error_echo

	local now="$(date +%Y%m%d_%s)"
	local bak_dir_path="${HOME}/.backup/${bspwmrc_dir_name}.bak"
	local bak_target_path="${bak_dir_path}/${bspwmrc_dir_name}.bak.${now}"

	util_error_echo "mkdir -p ${bak_dir_path}"
	mkdir -p "${bak_dir_path}"


	util_error_echo "cp -a ${bspwmrc_dir_path} ${bak_target_path}"
	cp -a "${bspwmrc_dir_path}" "${bak_target_path}"

	if [ "$?" != "0" ]; then
		util_error_echo
		util_error_echo '## Backup Failure!'
		#exit 1
		return 1
	fi

	util_error_echo


	return 0
}


bspwmrc_profile_init_dir () {

	if ! [ -d "$THE_BSPWMRC_PROFILE_DIR_PATH" ]; then
		##echo "$THE_BSPWMRC_PROFILE_DIR_PATH"
		mkdir -p "$THE_BSPWMRC_PROFILE_DIR_PATH"
	fi

	return 0
}


bspwmrc_repo_clone () {

	## $ bspwmrc-get demo

	local name="$1"
	local repo_url="$2"

	if [ "none$name" == 'none' ]; then
		name='default'
	fi

	util_error_echo "mkdir -p $THE_BSPWMRC_PROFILE_DIR_PATH"
	mkdir -p "$THE_BSPWMRC_PROFILE_DIR_PATH"

	util_error_echo "cd $THE_BSPWMRC_PROFILE_DIR_PATH"
	cd "$THE_BSPWMRC_PROFILE_DIR_PATH" ## cd ~/.local/share/bspwmrc-profile


	if [ -d "$name" ]; then
		util_error_echo
		util_error_echo "## Is Exists:" "$THE_BSPWMRC_PROFILE_DIR_PATH/$name"
		return 0;
	fi

	util_error_echo "git clone --recursive $repo_url $name "
	git clone --recursive "$repo_url" "$name"  ## git clone --recursive https://github.com/conformal/bspwm.git demo

	## $ man cd
	util_error_echo "cd $OLDPWD"
	cd "$OLDPWD"

}

##
### Tail: Sys
################################################################################


################################################################################
### Head: Model fzf
##

mod_fzf () {
	#echo "mod_fzf"
	#echo "$@"

	if ! is_command_exist 'fzf'; then

		util_error_echo '## Need: fzf'
		util_error_echo '# * https://github.com/junegunn/fzf'
		util_error_echo
		util_error_echo '## Manjaro Install:'
		util_error_echo '# $ pamac install fzf'
		util_error_echo
		util_error_echo '## Ubuntu Install:'
		util_error_echo '# $ sudo apt-get install fzf'
		util_error_echo

		return 1
	fi


	#https://en.wikipedia.org/wiki/Here_document
local selected="$(fzf << EOF
all
demo
EOF
)"


	util_error_echo
	util_error_echo "## Selected:"
	#util_error_echo

	if [ "none$selected" = "none" ]; then
		util_error_echo "# ! None Selected !"
		return 1
	fi

	util_error_echo "# [ $selected ]"
	main_run_sub_cmd "$selected"


}

##
### Tail: Model fzf
################################################################################


################################################################################
### Head: Model all_install
##

mod_all_install () {
	mod_demo_install
}



##
### Tail: Model all_install
################################################################################


################################################################################
### Head: Model demo
##

mod_demo_install () {
	util_error_echo
	util_error_echo "Todo: mod_demo_install"
	## mod_demo_repo_clone "$1" 'https://github.com/samwhelp/note-about-bspwm.git'
	##bspwmrc_repo_clone 'demo' 'https://github.com/samwhelp/note-about-bspwm.git'
	util_error_echo
}

##
### Tail: Model demo
################################################################################


################################################################################
### Head: SubCmd
##

sub_run_help () {
	main_usage "$@"
}

sub_run_version () {
	main_version "$@"
}

sub_run_self_update () {
	util_self_update "$@"
}

sub_run_self_actions () {
	util_self_actions "$@"
}



sub_run_fzf () {
	#echo "sub_run_fzf"
	mod_fzf "$@"
}


sub_run_all () {
	#echo "sub_run_all"
	mod_all_install "$@"
}


sub_run_demo () {
	#echo "sub_run_demo"
	mod_demo_install "$@"
}

##
### Tail: SubCmd
################################################################################


################################################################################
### Head: Main
##

main_usage () {
	##local cmd_name="$0"
	local cmd_name="$THE_CMD_FILE_NAME"

cat << EOF
Usage:
	$ $cmd_name [action]

Example:

	## help

		$ $cmd_name
		$ $cmd_name help

	## version

		$ $cmd_name version

	## self_update

		$ $cmd_name self_update

	## self_actions

		$ $cmd_name self_actions

	## fzf

		$ $cmd_name fzf

	## profile

		$ $cmd_name all

		$ $cmd_name demo


Debug:
	$ export DEBUG_BSPWMRC_GET=true

EOF

}

main_check_args_size () {
	if [ $1 -le 0 ]; then
		shift
		main_run_default_sub_cmd "$@"
		exit 1
	fi
}

main_run_default_sub_cmd () {
	main_usage "$@"
}

main_run_sub_cmd () {

	local sub_cmd="$1"

	shift

	local function_name=$(sub_cmd_find_function_name "$sub_cmd")

	## if ! command -v $function_name > /dev/null; then
	if ! type -p $function_name > /dev/null; then
		util_debug_echo "[Debug] sub_cmd_function_not_exist: sub_cmd=$sub_cmd; function_name=$function_name"

		echo
		main_run_default_sub_cmd "$@"
		return 1
	fi

	"$function_name" "$@" ## run sub cmd function


}

## Start
main_check_args_size $# "$@"

main_run_sub_cmd "$@"

##
### Tail: Main
################################################################################
